/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spring.events;

import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.stereotype.Component;

@Component//or Service or Repository
public class MainApp {
	
   
    public static void main(String[] args) {
    	try (AnnotationConfigApplicationContext ctx = 
    			new AnnotationConfigApplicationContext(SynchronousSpringEventsConfig.class)) {
    		
    	}
    }
}
